name: SSH to EC2 and Run Script

on:
  workflow_dispatch:

jobs:
  run-script-on-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set permissions on key
        run: |
          chmod 400 scripts/dev-ec2.pem
          ls -lrth scripts

      - name: SSH to EC2 and run script
        run: |
          ssh -i scripts/dev-ec2.pem -o StrictHostKeyChecking=no ec2-user@43.204.38.237 << 'EOF'
            chmod +x scripts/dev.sh
            ./scripts/dev.sh
            ls -l scripts
          EOF
