name: SSH to EC2 and Run Script

on:
  workflow_dispatch: # Trigger manually

jobs:
  run-script-on-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          cd /home/runner
          mkdir git-code
          cd git-code
          git clone https://github.com/sandeshhypha-eng/scripts.git
          chmod 400 scripts/dev-ec2.pem
          ls -lrth
          pwd

      - name: SSH to EC2 and run script
        run: |
          ls -lrth
          pwd
          cd /home/runner/git-code/scripts
          ssh -i "dev-ec2.pem" ec2-user@ec2-43-204-38-237.ap-south-1.compute.amazonaws.com << 'EOF'
            # Navigate to workspace
            cd ~
            # If repo exists, pull latest; else clone
            if [ -d "scripts" ]; then
              cd scripts && git pull
            else
              git clone https://github.com/sandeshhypha-eng/scripts.git
              cd scripts
            fi
            # Make script executable
            chmod +x dev.sh
            # Execute the script
            ./dev.sh
            ls
          EOF
